### ISSUE TITLE
Memory Leak: longPressReorderDelegate creates strong reference cycle

### ISSUE THREAD

**Issue by Laptopmini** [nicolasgomollon/LPRTableView#20]
The definition of `longPressReorderDelegate` creates a strong reference cycle when used, which means the class you assign to it is never `deinit()` which creates a memory leak.

This is because the delegate is declared as:
```
open var longPressReorderDelegate: LPRTableViewDelegate!
```

When it should be:
```
weak open var longPressReorderDelegate: LPRTableViewDelegate?
```

Notice I also removed the forced unwrap as delegates should always be optionally unwrapped. Which is done everywhere in the code, so it's surprising it was declared as such.

**Comment by nicolasgomollon** [comment]
Fixed in commit 660c29e8322380086cfa69b43481f31793747660.
