### ISSUE TITLE
Odd behaviour when height for cell larger than the standard height in iOS 11

### ISSUE THREAD

**Issue by edwinfinch** [nicolasgomollon/LPRTableView#22]
Hi there, absolutely love the library. 

I recently discovered an issue in testing that is easily reproducible. I'm going to try and fix it myself though I figured I'd share it here too in case anyone else already has a solution.

**Issue**
When the cell height is greater than the standard height (which I believe is 44), and you move a cell near the bottom of the table view, the cells jump around the screen in an odd manner. Please note you have to have more cells than can fit on the screen to reproduce this.

**Video demonstration**

https://www.youtube.com/watch?v=MlTH87Wj7so

**Steps to reproduce**

0. I believe this issue may only occur on iOS 11. I cannot reproduce it on an iPad running iOS 9.3.5 or an iPhone 6 running iOS 10.3.3, so ensure you're running iOS 11.

1. Override `func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat` and return a value of 100 (my testing value).

2. Ensure there are at least 2 "full screens" worth of rows.

3. Go to the bottom of the table view, begin to drag & drop any cell near the bottom. Move it upwards or downwards and notice the odd behaviour.

Thanks for reading!
Edwin

**Comment by edwinfinch** [comment]
Fixed!

From iOS 11 beta 2, this note was made:

> Table views now use estimated heights by default, which also means that cells and section header/footer views now self-size by default. The default value of the estimatedRowHeight, estimatedSectionHeaderHeight, and estimatedSectionFooterHeight properties is now UITableViewAutomaticDimension, which means the table view selects an estimated height to use. You should still provide a more accurate estimate for each property if possible, which is your best guess of the average value of the actual heights. If you have existing table view code that behaves differently when you build your app with the iOS 11 SDK, and you don’t want to adopt self-sizing, you can restore the previous behavior by disabling estimated heights by setting a value of zero for each estimated height property.

With that information, adding the following to `fileprivate func initialize()` within the LPRTableView class fixed the issue for me:

```
self.estimatedRowHeight = 0
self.estimatedSectionHeaderHeight = 0
self.estimatedSectionFooterHeight = 0
```

**Comment by nicolasgomollon** [comment]
Nice catch! Thanks for documenting this and for the quick fix!

**Comment by edwinfinch** [comment]
You got it 😃
