### ISSUE TITLE
Dragging a cell to the a different row too fast will mess up more rows

### ISSUE THREAD

**Issue by mdcoin** [nicolasgomollon/LPRTableView#5]
Hello, I'll use this opportunity to say thank you for sharing this with us.

I ran into an issue that I'm trying to solve with your approach at dragging cells. 
I suspect the problem is somewhere around the
 //reload the rows that were affected just to be safe
or at the moveRowAtIndexPath function.

When you drag the cell slow and gentle everything works perfectly but when you drag the cell fast and kind of drop it as if you wouldn't care where it will land or you move it around the table quick without releasing and then drop it quick what will happen is that more than one cell will chage it's text as if more than one cell's content has moved it's row. It just looks like if you release the cell before it falls into the new row it will call the moveRowAtIndexPath more than once. 

Say we have 7 rows that display 1 to 7 in ascending order and we drag a cell and move it quick and drop and let's say it landed at 2, instead of only the cell 7 and 2 to switch positions another random cell pair along the path(in this case 4 and 5) will change the position and the result will look like.

1
7
3
5
4
6
2

The more rows you have the more likely this will happen.
I hope I was clear enough. Let me know if you need a video to demonstrate this.

Thank you!

**Comment by nicolasgomollon** [comment]
Thanks for letting me know! I’m pretty sure I fixed it with this commit, but I’m still not exactly sure why this was happening in the first place.

**Comment by mdcoin** [comment]
Thanks, I spent a long night and couldn't figure it out :). 
It looks like you were swapping the source with the destination in 2 steps(2 separate lines) and when you do it quick enough the source and the destination change more than once until the scrolling stops...now the scrolling comes to a full stop as soon as you drop it.
Thanks again!
