### ISSUE TITLE
Some compile error

### ISSUE THREAD

**Issue by xgdgsc** [nicolasgomollon/LPRTableView#6]
I' m using Xcode 6.4. It compiles shows 2 error on the following code:

```
public convenience override init()  {
        self.init(frame: CGRectZero)
    }
```

removing the `override` fixed the error of `LPRTableView.swift:55:30: Initializer does not override a designated initializer from its superclass`.

```
public var lprTableView: LPRTableView! { return tableView as LPRTableView }
```

changing `as` to `as!` fixed the error of `LPRTableView.swift:304:60: 'UITableView!' is not convertible to 'LPRTableView'; did you mean to use 'as!' to force downcast?`

**Comment by nicolasgomollon** [comment]
Looks like this one slipped through the cracks. Thanks for pointing it out!

Fixed in 90345667040025ac74a080c743b96ff23ab2ff54.
