### ISSUE TITLE
not working with `UITableViewAutomaticDimension`.

### ISSUE THREAD

**Issue by kunass2** [nicolasgomollon/LPRTableView#8]
Can you fix this issue?:-)

**Comment by cliftonlabrum** [comment]
Did you ever figure this out? I just realized it's broken, too.

**Comment by kunass2** [comment]
no, unfortunately not;-(

**Comment by shadowpath** [comment]
Found the fix for this. 
Remove these from LPRTableView's `fileprivate func initialize()`

```
estimatedRowHeight = 0.0
estimatedSectionHeaderHeight = 0.0
estimatedSectionFooterHeight = 0.0
```
